// Human-readable title + "why it matters" copy for every check ID. The dynamic `detail` string
// each check already computes (e.g. "3 of 5 images missing alt text") carries the specific
// finding; this file only carries the static, always-true explanation of the check itself.
export const CHECK_META: Record<string, { title: string; why: string }> = {
  'keyword.primary_exists': { title: 'Focus keyphrase set', why: 'Every other keyword check depends on having one clear phrase to target.' },
  'keyword.in_title': { title: 'Keyphrase in SEO title', why: 'The title is the single strongest on-page relevance signal.' },
  'keyword.title_position': { title: 'Keyphrase near the start of the title', why: 'Search engines and readers weigh the first words of a title more heavily.' },
  'keyword.in_description': { title: 'Keyphrase in meta description', why: 'Helps the snippet read as directly relevant to the search query.' },
  'keyword.in_slug': { title: 'Keyphrase in URL slug', why: 'A descriptive URL is a small but real relevance and click-through signal.' },
  'keyword.in_h1': { title: 'Keyphrase in H1', why: 'The H1 should state what the page is about in the same terms a reader searched for.' },
  'keyword.in_introduction': { title: 'Keyphrase in the introduction', why: 'Confirms the topic early for both readers and crawlers.' },
  'keyword.in_subheadings': { title: 'Keyphrase reflected in subheadings', why: 'Natural, not forced — subheadings should still track the page’s topic.' },
  'keyword.density': { title: 'Keyphrase density', why: 'Too rare and relevance is unclear; too frequent reads as keyword stuffing.' },
  'keyword.related_usage': { title: 'Related keyphrases used', why: 'Related terms help cover the topic’s natural vocabulary.' },
  'metadata.title_exists': { title: 'SEO title set', why: 'Without one, the app falls back to a generic default title.' },
  'metadata.title_length': { title: 'SEO title length', why: 'Titles outside the recommended range are likely to be truncated or too thin.' },
  'metadata.title_unique': { title: 'SEO title is unique', why: 'Two pages with the same title compete with each other instead of ranking independently.' },
  'metadata.description_exists': { title: 'Meta description set', why: 'Improves the search snippet instead of leaving it to an automatic excerpt.' },
  'metadata.description_length': { title: 'Meta description length', why: 'Outside the recommended range, the snippet is likely truncated or too thin.' },
  'metadata.description_unique': { title: 'Meta description is unique', why: 'Duplicate descriptions blur the distinction between pages in search results.' },
  'metadata.canonical_exists': { title: 'Canonical URL set', why: 'Declares the definitive URL for this content explicitly.' },
  'metadata.canonical_https_absolute': { title: 'Canonical is absolute HTTPS', why: 'A relative or non-HTTPS canonical can be misread by crawlers.' },
  'metadata.robots_directive': { title: 'Robots directive', why: 'Shows the current index/follow setting for this page.' },
  'metadata.og_title': { title: 'Open Graph title', why: 'Controls how the page’s title appears when shared on social platforms.' },
  'metadata.og_description': { title: 'Open Graph description', why: 'Controls the description shown in social share previews.' },
  'metadata.og_image': { title: 'Open Graph image', why: 'A page-specific share image performs better than the generic branded default.' },
  'content.single_h1': { title: 'Exactly one H1', why: 'A single, clear H1 defines the page’s main topic for readers and crawlers.' },
  'content.heading_structure': { title: 'Heading order', why: 'Skipping levels (H2 straight to H4) breaks the logical outline of the page.' },
  'content.word_count': { title: 'Content length', why: 'Guidance only, and page-type aware — short pages by nature (Contact, utility) are never penalized for length.' },
  'content.introduction_present': { title: 'Introduction present', why: 'Orients the reader (and the crawler) before the detail sections.' },
  'content.duplicate_headings': { title: 'No duplicate headings', why: 'Repeated identical headings make the outline harder to scan and can look templated.' },
  'content.empty_headings': { title: 'No empty headings', why: 'An empty heading tag is usually a content-editing mistake.' },
  'content.faq_presence': { title: 'FAQ content', why: 'Expected for this page type — supports FAQ rich results where genuinely applicable.' },
  'content.cta_presence': { title: 'Call to action present', why: 'Expected for this page type — the page should tell the reader what to do next.' },
  'readability.sentence_length': { title: 'Sentence length', why: 'Consistently long sentences are harder to read on any device.' },
  'readability.paragraph_length': { title: 'Paragraph length', why: 'Long unbroken paragraphs are harder to scan, especially on mobile.' },
  'readability.passive_voice': { title: 'Passive voice', why: 'Active voice generally reads as more direct and confident.' },
  'readability.transition_words': { title: 'Transition words', why: 'Transition words help ideas flow logically from one sentence to the next.' },
  'readability.subheading_distribution': { title: 'Subheading distribution', why: 'Regular subheadings let readers scan long content instead of a wall of text.' },
  'readability.consecutive_sentence_starts': { title: 'Sentence-opener variety', why: 'Starting many sentences the same way reads as repetitive.' },
  'links.internal_count': { title: 'Internal links present', why: 'Internal links help both readers and crawlers navigate related content.' },
  'links.outgoing_present': { title: 'Outgoing links', why: 'A page with zero links anywhere is unusually isolated.' },
  'links.generic_anchor_text': { title: 'Descriptive anchor text', why: '"Click here" tells a reader (and a crawler) nothing about the destination.' },
  'links.incoming_count': { title: 'Incoming internal links', why: 'A page nothing links to is hard for both users and crawlers to discover.' },
  'links.external_security': { title: 'Safe external links', why: 'A new-tab external link without rel="noopener" is a minor but real security gap.' },
  'images.missing_alt': { title: 'Images have alt text', why: 'Alt text is read by screen readers and used by image search — required for meaningful images.' },
  'images.alt_quality': { title: 'Alt text is descriptive', why: 'Generic alt text like "image" is functionally the same as missing alt text.' },
  'images.missing_dimensions': { title: 'Images have width/height', why: 'Missing dimensions let the image cause layout shift while loading.' },
  'images.count': { title: 'Image count', why: 'Informational — not every page needs images.' },
  'technical.indexable': { title: 'Indexability matches page type', why: 'Confirms robots index/noindex matches what this page type normally expects.' },
  'technical.canonical_matches_page': { title: 'Canonical points to this page', why: 'A canonical pointing elsewhere tells search engines this page isn’t the authoritative version.' },
  'technical.structured_data_present': { title: 'Structured data present', why: 'Schema helps search engines understand and potentially enhance this page’s listing.' },
  'technical.unique_slug': { title: 'URL slug is unique', why: 'A duplicate slug across content types is a routing conflict, not just an SEO issue.' },
};
